### ISSUE TITLE
How to automatically change slow start duration 

### ISSUE THREAD

**Issue by tencoder** [Senzing/aws-cloudformation-ecs-senzing-stack-basic#141]
Hi, thanks for your contribution. I see that you hard coded slow_start.duration_seconds in the yaml file, how can I set it to accept a slow start duration value from say a fargate.json file?

Any hint or resource would be much appreciated.
Thank you.

**Comment by roncewind** [comment]
Hi there @tencoder!  First off, I would encourage you to take the CloudFormation template and modify it as you see fit.  We offer them as and example and fully expect your deployment situation to be different from what we have in our CFT.  To directly address your question, I think if you take a look at:  https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-target-group-attributes.html  You'll find that you can update `slow_start.duration_seconds` via the CLI using a `cli-input-json`.  I hope I've understood your question correctly and my answer helps you.  Feel free to ask more and I'll do my best to help.  Thanks!  --@roncewind.

**Comment by roncewind** [comment]
Hey @tencoder Let us know if this works for you.  If we don't hear from you in a week I'll go ahead and close this.  thanks!
