### ISSUE TITLE
Support mixed case stack names

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-ecs-senzing-stack-basic#4]
**Is your feature request related to a problem? Please describe.**
When using a stackname containing upper-case letters, the following error is seen in the Cloudformation events:

**UserPoolDomain**
> The domain name contains an invalid character. Domain names can only contain lower-case letters, numbers, and hyphens. Please enter a different name that follows this format: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$ (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxxx; Proxy: null)

**Describe the solution you'd like**
Determine how to support Mixed case stacknames, yet have lower-case name for `UserPoolDomain`.

Note: This was tried once, but there were problems with Cognito.

**Comment by roncewind** [comment]
PR merged
