### ISSUE TITLE
LambdaRunnerSubnets: CREATE_FAILED

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/aws-cloudformation-ecs-senzing-stack-basic#6]
The stack fails to complete and rolls back successfully. 

See first line error:
LambdaRunnerSubnets > CREATE_FAILED
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/05/13/[$LATEST]b7d282f512b64be4abf5e8f1f47525e7 (RequestId: 978e3235-109d-45af-9b8e-233304f01862)

**Comment by docktermj** [comment]
@christianswanepoel Need more information.  Can you post the contents of the log>

**Comment by christianswanepoel** [comment]
@docktermj to be honest I tried finding the log - but couldn't 
Where would it be hiding from me :)

**Comment by docktermj** [comment]
1. https://console.aws.amazon.com/cloudwatch/home?#logsV2:log-groups
2. On left-hand navigation bar, choose "Log Groups"
3. Choose /aws/lambda/{StackName}-lambda-subnets

**Comment by christianswanepoel** [comment]
Yeah - not there
<img width="1640" alt="Screenshot 2021-05-13 at 16 29 43" src="https://user-images.githubusercontent.com/7249713/118140520-b8513580-b408-11eb-8251-8170b700a1a0.png">

**Comment by christianswanepoel** [comment]
Morning @docktermj 
I saw the YAML updated and tried to see if it fixed my issue - it has not, and there's still no relevant cloudformation log to debug the issue.

**Comment by docktermj** [comment]
Hi @christianswanepoel !

I'm half done testing https://github.com/Senzing/aws-cloudformation-ecs/blob/issue-34.dockter.2/cloudformation/aws-cloudformation-ecs-senzing-stack-with-choices/cloudformation.yaml which allows a user to pick-and-choose the services needed at deployment time without having to modify the Cloudformation Template.  This template should satisfy your needs.

**Comment by christianswanepoel** [comment]
But please note... these errors are from the unedited default install YAML. I.e clicking on the link as per the instructions.

**Comment by docktermj** [comment]
@christianswanepoel What AWS Region are you running in?   (I know I've asked before, but I've forgotten)

**Comment by christianswanepoel** [comment]
We in eu-west-1 ;)

**Comment by christianswanepoel** [comment]
Hi @docktermj - your latest build woks. I can install the default base install without error. 
looking forward to the configurable service version.

**Comment by docktermj** [comment]
Hi @christianswanepoel The "configurable" version is now at https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-choices
